### ISSUE TITLE
Interesting result - not sure I understand generation of time component

### ISSUE THREAD

**Issue by mvinyard** [simupy/simupy#15] opened 2020-04-28 18:05 UTC
Hi there,

You helped me several months ago with getting started using simupy! I am back with a question regarding some results I have. 

When I simulate data using the following set of ODEs:
```
def state_eqn(time, states): 
    x, y = states
    xdot = -x + y**2
    ydot = -y - x*y
    return np.array([xdot, ydot])
```
I obtain: 
![res1](https://user-images.githubusercontent.com/47393421/80520826-fdb6d800-8957-11ea-95b4-459fc36e907e.png)

Then, I try to recover time using this equation to return time, based on the simulated x,y points and the local velocity at each observed point:
<img width="218" alt="Screen Shot 2020-04-28 at 2 04 54 PM" src="https://user-images.githubusercontent.com/47393421/80521580-44f19880-8959-11ea-9151-37279e858e33.png">

This is what I obtain where I have highlighted the simupy-generated time in green and my estimated time (using the time eqn above) in red:

<img width="1016" alt="Screen Shot 2020-04-28 at 2 00 16 PM" src="https://user-images.githubusercontent.com/47393421/80521188-9e0cfc80-8958-11ea-99ba-24a5722205ed.png">

As you can see, it's really close in the beginning, but very off in the end, as the system approaches zero. I am wondering if this has something to do with the way time is simulated and I thought you might know the answer?

Additionally, this is what time looks like on the axis of simulated points on the curve - I am confused as to why it is bimodal; I am wondering if it has something to do with it approaching zero, but I'm really not sure why?

![image](https://user-images.githubusercontent.com/47393421/80521339-df9da780-8958-11ea-90cf-800964aacd7f.png)

**Comment by mvinyard** [comment] 2020-04-29 16:41
As an update: I re-performed my calculations using numpy and mpmath such that I lose no precision even with very tiny numbers. It doesn't seem to help. I will try log-transforming the numbers but I have a feeling it may not have to do with precision.

**Comment by sixpearls** [comment] 2020-05-16 18:49
Hi @mvinyard -- The default ODE integrator is "dopri5" with adaptive step sizes as shown in the [docs](https://simupy.readthedocs.io/en/latest/api/block_diagram.html#simupy.block_diagram.BlockDiagram.simulate). This seems to be a research question/analysis discussion, not a bug with SimuPy, so I'm going to close this. Good luck!

**Closed** 2020-05-16 18:49 UTC
